import {InnerHero,SiteShell} from "../../site-shell";

const selected=[
  {number:"01",name:"CODA",full:"Calidad de Objetos de Aprendizaje",reason:"Ofrece una guía operativa para valorar conjuntamente la calidad didáctica y tecnológica. Sus diez criterios permiten reconocer tanto la coherencia pedagógica como las condiciones de uso, reutilización e interoperabilidad.",instrument:"Formulario de diez criterios puntuados de 1 a 5, con opción «no aplicable» y justificación cualitativa.",strengths:["Aplicación directa","Equilibrio didáctico y técnico","Orienta mejoras concretas"],limits:["Fue creado inicialmente para objetos de aprendizaje universitarios","Algunos indicadores requieren adaptación al contexto escolar"],source:"https://docta.ucm.es/entities/publication/4593272d-230f-4d4f-9488-4a4b36ca0a5c"},
  {number:"02",name:"LORI",full:"Learning Object Review Instrument",reason:"Permite construir un perfil comparable de calidad mediante nueve dimensiones. Resulta útil para contrastar los dos RED con una escala común y registrar evidencias junto con cada puntuación.",instrument:"Rúbrica de nueve dimensiones valoradas de 1 a 5, con «no aplicable» y espacio para comentarios.",strengths:["Estructura reconocida","Comparación clara entre recursos","Integra accesibilidad y estándares"],limits:["La puntuación depende del juicio experto","Requiere justificar cada valoración para evitar resultados superficiales"],source:"https://www.sfu.ca/~jcnesbit/articles/leacocknesbit2007.htm"},
  {number:"03",name:"REEVES",full:"Dimensiones pedagógicas de la educación basada en computador",reason:"Complementa CODA y LORI al revelar la concepción pedagógica que sostiene cada RED. Sus continuos permiten analizar construcción del conocimiento, experiencia, flexibilidad, autonomía, actividad, cooperación y el papel mediador de la docente.",instrument:"Matriz gráfica de catorce dimensiones bipolares. Cada recurso se ubica entre los dos polos de cada continuo para construir un perfil pedagógico; no produce por sí sola una nota universal de calidad.",strengths:["Pertinente para contextos escolares","Explicita el enfoque pedagógico","Analiza roles, autonomía y cooperación"],limits:["Requiere interpretar cada continuo según el contexto","No integra por sí solo todos los requisitos técnicos y de accesibilidad"],source:"https://www.eduworks.com/Documents/Workshops/EdMedia1998/docs/reeves.html"}
];

const evaluations=[
  {model:"CODA",resource:"Analiza a los maestros",image:"/images/evaluations/coda-analiza.png",pdf:"/documents/coda-dos-red.pdf",page:1,summary:"Valoración mediante diez criterios didácticos y tecnológicos."},
  {model:"CODA",resource:"Gaia, conociendo nuestro mundo",image:"/images/evaluations/coda-gaia.png",pdf:"/documents/coda-dos-red.pdf",page:8,summary:"Aplicación de los diez criterios a la situación de aprendizaje de INTEF."},
  {model:"LORI",resource:"Analiza a los maestros",image:"/images/evaluations/lori-analiza.png",pdf:"/documents/lori-dos-red.pdf",page:1,summary:"Revisión del recurso mediante las nueve dimensiones de calidad de LORI."},
  {model:"LORI",resource:"Gaia, conociendo nuestro mundo",image:"/images/evaluations/lori-gaia.png",pdf:"/documents/lori-dos-red.pdf",page:7,summary:"Revisión comparada de contenido, diseño, uso y posibilidades educativas."},
  {model:"REEVES",resource:"Analiza a los maestros",image:"/images/evaluations/reeves-analiza.png",pdf:"/documents/reeves-dos-red.pdf",page:1,summary:"Perfil del recurso a partir de catorce dimensiones pedagógicas."},
  {model:"REEVES",resource:"Gaia, conociendo nuestro mundo",image:"/images/evaluations/reeves-gaia.png",pdf:"/documents/reeves-dos-red.pdf",page:9,summary:"Lectura del enfoque pedagógico, la actividad y la autonomía del estudiante."}
];

export default function Page(){return <SiteShell active="modelos">
  <InnerHero number="2.1" kicker="Subpágina · Seleccionando modelos" title="Tres instrumentos, dos recursos" summary="CODA, LORI y Reeves permiten observar los RED desde perspectivas complementarias y construir una comparación sustentada en evidencia."/>
  <section className="selection-opening"><div><span>DECISIÓN METODOLÓGICA</span><h2>Una selección complementaria, no redundante.</h2></div><p>Los tres modelos comparten criterios de calidad, pero difieren en profundidad y enfoque. CODA equilibra didáctica y tecnología; LORI ofrece una lectura integral comparable; Reeves revela la orientación pedagógica, el nivel de actividad, la autonomía, la cooperación y el papel de la docente.</p></section>
  <figure className="selection-visual"><img src="/images/models-workspace-v2.png" alt="Equipo académico revisando instrumentos de evaluación de recursos educativos digitales"/><figcaption>La triangulación de instrumentos reduce la dependencia de una única perspectiva evaluativa.</figcaption></figure>
  <section className="selection-video" aria-labelledby="selection-video-title">
    <div className="selection-video-copy"><span>RECURSO AUDIOVISUAL</span><h2 id="selection-video-title">Modelos de evaluación de Recursos Educativos Digitales</h2><p>Esta síntesis audiovisual introduce los criterios que orientan la selección de CODA, LORI y Reeves y facilita la comprensión de sus enfoques complementarios.</p></div>
    <div className="selection-video-frame"><iframe src="https://www.youtube-nocookie.com/embed/mDPcKtQKFL0?rel=0&thumbnailRefresh=20260815" title="Video: Modelos de evaluación de Recursos Educativos Digitales" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe></div>
  </section>
  <section className="selected-models">{selected.map(m=><article key={m.name} id={`seleccion-${m.name.toLowerCase()}`}><header><span>{m.number}</span><div><small>{m.full}</small><h2>{m.name}</h2></div></header><div className="selection-reason"><b>Razón de selección</b><p>{m.reason}</p></div><div className="selection-columns"><section><b>Instrumento que se aplicará</b><p>{m.instrument}</p></section><section><b>Ventajas</b><ul>{m.strengths.map(x=><li key={x}>{x}</li>)}</ul></section><section><b>Limitaciones</b><ul>{m.limits.map(x=><li key={x}>{x}</li>)}</ul></section></div><a href={m.source} target="_blank" rel="noreferrer" className="source-link">Consultar fuente verificada <span>↗</span></a></article>)}</section>
  <section className="application-plan"><div><span>APLICACIÓN DE LOS INSTRUMENTOS</span><h2>Seis evaluaciones</h2><p>CODA, LORI y Reeves fueron aplicados por separado a los dos RED. Cada evaluación presenta las puntuaciones, las observaciones y las evidencias que sustentan el análisis.</p></div><div className="application-matrix" role="table" aria-label="Aplicación de los tres modelos a los dos recursos"><div className="matrix-head" role="row"><b>Modelo</b><b>Analiza a los maestros</b><b>Gaia</b></div>{selected.map(m=><div role="row" key={m.name}><strong>{m.name}</strong><span>Evaluación completa</span><span>Evaluación completa</span></div>)}</div></section>
  <section className="evaluation-library" aria-labelledby="evaluation-library-title">
    <div className="evaluation-library-head"><span>EVIDENCIAS DOCUMENTALES</span><h2 id="evaluation-library-title">Consultar las seis evaluaciones</h2><p>Las seis aplicaciones están organizadas en tres documentos, uno por modelo. Cada tarjeta abre el PDF directamente en la evaluación del recurso correspondiente.</p></div>
    <div className="evaluation-groups">{selected.map(model=><section className="evaluation-group" key={model.name} aria-labelledby={`grupo-${model.name.toLowerCase()}`}><header><small>Modelo de evaluación</small><h3 id={`grupo-${model.name.toLowerCase()}`}>{model.name}</h3></header><div className="evaluation-card-grid">{evaluations.filter(item=>item.model===model.name).map(item=><article className="evaluation-card" key={`${item.model}-${item.resource}`}><div className="evaluation-card-preview"><img src={item.image} alt={`Primera página de la evaluación ${item.model} aplicada a ${item.resource}`}/><span>PDF · {item.model}</span></div><div className="evaluation-card-copy"><small>Recurso educativo digital</small><h4>{item.resource}</h4><p>{item.summary}</p><div className="evaluation-card-actions"><a href={`${item.pdf}#page=${item.page}`} target="_blank" rel="noreferrer">Ver evaluación <b>↗</b></a><a href={item.pdf} download>Descargar PDF <b>↓</b></a></div></div></article>)}</div></section>)}</div>
  </section>
  <section className="selection-conclusion selection-recommendation"><span>MODELO PERTINENTE PARA MI CONTEXTO</span><h2>CODA adaptado a la observación artística</h2><div className="recommendation-prose"><p>Después de aplicar los modelos CODA, LORI y Reeves a los dos recursos educativos digitales seleccionados, considero que CODA es el más pertinente para adaptar a mi contexto. Su estructura permite valorar de manera clara los contenidos, el diseño, la facilidad de uso y la utilidad pedagógica de cada recurso.</p><p>En mi práctica como docente de Educación Artística trabajo con estudiantes de bachillerato que presentan dificultades para observar con atención, reconocer proporciones y trasladar lo observado a ejercicios de dibujo. Por esta razón, necesito un modelo que permita identificar si un recurso realmente ayuda a mirar, comparar, interpretar y producir una evidencia artística.</p><p>CODA podría adaptarse incorporando criterios relacionados con la calidad de las imágenes, la secuencia observar–comparar–interpretar–dibujar, el tiempo de aplicación en clase, la orientación que debe brindar el docente y la posibilidad de utilizar el recurso cuando la conexión a internet es limitada.</p><p>LORI resulta útil para comparar recursos y Reeves permite reconocer el enfoque pedagógico de cada uno. Sin embargo, CODA responde mejor a las necesidades de mi práctica porque facilita tomar decisiones concretas sobre qué recurso seleccionar, qué aspectos modificar y cómo integrarlo a las actividades de Educación Artística.</p></div></section>
 </SiteShell>}
