import { SiteShell } from "./site-shell";

export default function Home(){return <SiteShell active="inicio">
  <section className="new-hero">
    <div className="hero-photo"><img src="/images/hero-academic-v2.png" alt="Docente analizando recursos educativos digitales"/><span className="photo-wash"/></div>
    <div className="hero-message reveal"><p className="micro">Portafolio académico · UDES · 2026</p><h1>Evaluación de<br/><em>Recursos Educativos</em><br/>Digitales</h1><p className="hero-motto">Evaluar lo digital con criterio humano.</p><p>Una exploración visual y argumentada de los modelos que permiten reconocer, comparar y mejorar la calidad de los recursos educativos digitales.</p><div className="hero-actions"><a className="button button-gold" href="/modelos-red">Comenzar recorrido <span>↗</span></a><a className="text-link" href="#proposito">Conocer el propósito <span>↓</span></a></div></div>
    <div className="hero-signature"><span>Evaluación de</span><strong>Recursos Educativos Digitales</strong></div>
  </section>
  <section className="credentials"><p><small>Autor</small>Jesús Alberto Giraldo Zapata</p><p><small>Profesora</small>Gloria Cecilia Ríos</p><p><small>Universidad</small>Universidad de Santander · UDES</p></section>
  <section className="purpose organic-section" id="proposito"><div className="section-tag">01 · PROPÓSITO</div><div><h2>La calidad no se supone.<br/><em>Se observa, se contrasta y se argumenta.</em></h2><p>Un recurso educativo digital no es valioso solo porque funciona. Debe articular contenido riguroso, intención pedagógica, experiencia accesible y una tecnología que permanezca al servicio del aprendizaje.</p><a className="round-link" href="/modelos-red"><span>Explorar criterios</span><b>→</b></a></div></section>
  <section className="visual-story"><div className="story-image reveal"><img src="/images/models-workspace-v2.png" alt="Mesa de trabajo para evaluar recursos educativos"/></div><div className="story-copy"><span>02 · TRES MIRADAS</span><h2>Modelos que convierten la intuición en evidencia.</h2><p>LORI, HEODAR y EVALUAREED ofrecen rutas distintas para examinar la calidad. El criterio decisivo no es elegir el modelo más famoso, sino el más pertinente para el recurso y su contexto.</p><div className="model-pills"><i>LORI</i><i>HEODAR</i><i>EVALUAREED</i></div><a className="button button-blue" href="/modelos-red">Comparar los modelos <span>→</span></a></div></section>
  <section className="criteria-flow"><div className="flow-head"><span>03 · DIMENSIONES</span><h2>Una lectura integral del recurso</h2></div><div className="flow-list">{['Contenido','Objetivos','Pedagogía','Retroalimentación','Motivación','Usabilidad','Accesibilidad','Adaptabilidad','Técnica','Autoría'].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div></section>
  <section className="redesign-feature"><div className="redesign-copy"><span>04 · TRANSFORMACIÓN</span><h2>Evaluar también significa imaginar una versión mejor.</h2><p>El diagnóstico adquiere sentido cuando conduce a decisiones concretas: reorganizar, aclarar, hacer accesible, enriquecer la interacción y comprobar que el cambio realmente mejora la experiencia educativa.</p><div className="dual-actions"><a className="button button-light" href="/rediseno">Ver proceso de rediseño <span>↗</span></a><a className="line-link" href="/aplicacion">Aplicación del modelo →</a></div></div><div className="redesign-photo"><img src="/images/redesign-process-v2.png" alt="Proceso de rediseño de un recurso educativo digital"/></div></section>
  <section className="closing"><p>Evaluar · comprender · transformar</p><h2>La tecnología educativa alcanza valor cuando responde con claridad a una necesidad humana.</h2><a href="/referencias" className="button button-gold">Consultar referencias <span>→</span></a></section>
 </SiteShell>}
